#############################################################################
# Makefile for building: labs.app/Contents/MacOS/labs
# Generated by qmake (2.01a) (Qt 4.7.4) on: ?? ???. 28 13:18:24 2012
# Project:  labs.pro
# Template: app
# Command: /Users/volodymyr/QtSDK/Desktop/Qt/474/gcc/bin/qmake -spec /Users/volodymyr/QtSDK/Desktop/Qt/474/gcc/mkspecs/macx-g++42 -o Makefile labs.pro
#############################################################################

####### Compiler, tools and options

CC            = gcc-4.2
CXX           = g++-4.2
DEFINES       = -DQT_GUI_LIB -DQT_CORE_LIB
CFLAGS        = -pipe -g -gdwarf-2 -arch x86_64 -Xarch_x86_64 -mmacosx-version-min=10.5 -Wall -W $(DEFINES)
CXXFLAGS      = -pipe -g -gdwarf-2 -arch x86_64 -Xarch_x86_64 -mmacosx-version-min=10.5 -Wall -W $(DEFINES)
INCPATH       = -I/Users/volodymyr/QtSDK/Desktop/Qt/474/gcc/mkspecs/macx-g++42 -I. -I/Users/volodymyr/QtSDK/Desktop/Qt/474/gcc/lib/QtCore.framework/Versions/4/Headers -I/Users/volodymyr/QtSDK/Desktop/Qt/474/gcc/include/QtCore -I/Users/volodymyr/QtSDK/Desktop/Qt/474/gcc/lib/QtGui.framework/Versions/4/Headers -I/Users/volodymyr/QtSDK/Desktop/Qt/474/gcc/include/QtGui -I/Users/volodymyr/QtSDK/Desktop/Qt/474/gcc/include -I. -I. -F/Users/volodymyr/QtSDK/Desktop/Qt/474/gcc/lib
LINK          = g++-4.2
LFLAGS        = -headerpad_max_install_names -arch x86_64 -Xarch_x86_64 -mmacosx-version-min=10.5
LIBS          = $(SUBLIBS) -F/Users/volodymyr/QtSDK/Desktop/Qt/474/gcc/lib -L/Users/volodymyr/QtSDK/Desktop/Qt/474/gcc/lib -framework QtGui -framework QtCore 
AR            = ar cq
RANLIB        = ranlib -s
QMAKE         = /Users/volodymyr/QtSDK/Desktop/Qt/474/gcc/bin/qmake
TAR           = tar -cf
COMPRESS      = gzip -9f
COPY          = cp -f
SED           = sed
COPY_FILE     = cp -f
COPY_DIR      = cp -f -R
STRIP         = 
INSTALL_FILE  = $(COPY_FILE)
INSTALL_DIR   = $(COPY_DIR)
INSTALL_PROGRAM = $(COPY_FILE)
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p
export MACOSX_DEPLOYMENT_TARGET = 10.4

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = main.cpp \
		mainwindow.cpp \
		crypto.cpp moc_mainwindow.cpp
OBJECTS       = main.o \
		mainwindow.o \
		crypto.o \
		moc_mainwindow.o
DIST          = /Users/volodymyr/QtSDK/Desktop/Qt/474/gcc/mkspecs/common/unix.conf \
		/Users/volodymyr/QtSDK/Desktop/Qt/474/gcc/mkspecs/common/mac.conf \
		/Users/volodymyr/QtSDK/Desktop/Qt/474/gcc/mkspecs/common/mac-g++.conf \
		/Users/volodymyr/QtSDK/Desktop/Qt/474/gcc/mkspecs/qconfig.pri \
		/Users/volodymyr/QtSDK/Desktop/Qt/474/gcc/mkspecs/modules/qt_webkit_version.pri \
		/Users/volodymyr/QtSDK/Desktop/Qt/474/gcc/mkspecs/features/qt_functions.prf \
		/Users/volodymyr/QtSDK/Desktop/Qt/474/gcc/mkspecs/features/qt_config.prf \
		/Users/volodymyr/QtSDK/Desktop/Qt/474/gcc/mkspecs/features/exclusive_builds.prf \
		/Users/volodymyr/QtSDK/Desktop/Qt/474/gcc/mkspecs/features/default_pre.prf \
		/Users/volodymyr/QtSDK/Desktop/Qt/474/gcc/mkspecs/features/mac/default_pre.prf \
		/Users/volodymyr/QtSDK/Desktop/Qt/474/gcc/mkspecs/features/mac/dwarf2.prf \
		/Users/volodymyr/QtSDK/Desktop/Qt/474/gcc/mkspecs/features/debug.prf \
		/Users/volodymyr/QtSDK/Desktop/Qt/474/gcc/mkspecs/features/default_post.prf \
		/Users/volodymyr/QtSDK/Desktop/Qt/474/gcc/mkspecs/features/mac/default_post.prf \
		/Users/volodymyr/QtSDK/Desktop/Qt/474/gcc/mkspecs/features/mac/x86_64.prf \
		/Users/volodymyr/QtSDK/Desktop/Qt/474/gcc/mkspecs/features/mac/objective_c.prf \
		/Users/volodymyr/QtSDK/Desktop/Qt/474/gcc/mkspecs/features/warn_on.prf \
		/Users/volodymyr/QtSDK/Desktop/Qt/474/gcc/mkspecs/features/qt.prf \
		/Users/volodymyr/QtSDK/Desktop/Qt/474/gcc/mkspecs/features/unix/thread.prf \
		/Users/volodymyr/QtSDK/Desktop/Qt/474/gcc/mkspecs/features/moc.prf \
		/Users/volodymyr/QtSDK/Desktop/Qt/474/gcc/mkspecs/features/mac/rez.prf \
		/Users/volodymyr/QtSDK/Desktop/Qt/474/gcc/mkspecs/features/mac/sdk.prf \
		/Users/volodymyr/QtSDK/Desktop/Qt/474/gcc/mkspecs/features/resources.prf \
		/Users/volodymyr/QtSDK/Desktop/Qt/474/gcc/mkspecs/features/uic.prf \
		/Users/volodymyr/QtSDK/Desktop/Qt/474/gcc/mkspecs/features/yacc.prf \
		/Users/volodymyr/QtSDK/Desktop/Qt/474/gcc/mkspecs/features/lex.prf \
		/Users/volodymyr/QtSDK/Desktop/Qt/474/gcc/mkspecs/features/include_source_dir.prf \
		labs.pro
QMAKE_TARGET  = labs
DESTDIR       = 
TARGET        = labs.app/Contents/MacOS/labs

####### Custom Compiler Variables
QMAKE_COMP_QMAKE_OBJECTIVE_CFLAGS = -pipe \
		-g \
		-gdwarf-2 \
		-arch \
		x86_64 \
		-Xarch_x86_64 \
		-mmacosx-version-min=10.5 \
		-Wall \
		-W


first: all
####### Implicit rules

.SUFFIXES: .o .c .cpp .cc .cxx .C

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.C.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o "$@" "$<"

####### Build rules

all: Makefile labs.app/Contents/PkgInfo labs.app/Contents/Resources/empty.lproj labs.app/Contents/Info.plist $(TARGET)

$(TARGET): ui_mainwindow.h $(OBJECTS)  
	@$(CHK_DIR_EXISTS) labs.app/Contents/MacOS/ || $(MKDIR) labs.app/Contents/MacOS/ 
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: labs.pro  /Users/volodymyr/QtSDK/Desktop/Qt/474/gcc/mkspecs/macx-g++42/qmake.conf /Users/volodymyr/QtSDK/Desktop/Qt/474/gcc/mkspecs/common/unix.conf \
		/Users/volodymyr/QtSDK/Desktop/Qt/474/gcc/mkspecs/common/mac.conf \
		/Users/volodymyr/QtSDK/Desktop/Qt/474/gcc/mkspecs/common/mac-g++.conf \
		/Users/volodymyr/QtSDK/Desktop/Qt/474/gcc/mkspecs/qconfig.pri \
		/Users/volodymyr/QtSDK/Desktop/Qt/474/gcc/mkspecs/modules/qt_webkit_version.pri \
		/Users/volodymyr/QtSDK/Desktop/Qt/474/gcc/mkspecs/features/qt_functions.prf \
		/Users/volodymyr/QtSDK/Desktop/Qt/474/gcc/mkspecs/features/qt_config.prf \
		/Users/volodymyr/QtSDK/Desktop/Qt/474/gcc/mkspecs/features/exclusive_builds.prf \
		/Users/volodymyr/QtSDK/Desktop/Qt/474/gcc/mkspecs/features/default_pre.prf \
		/Users/volodymyr/QtSDK/Desktop/Qt/474/gcc/mkspecs/features/mac/default_pre.prf \
		/Users/volodymyr/QtSDK/Desktop/Qt/474/gcc/mkspecs/features/mac/dwarf2.prf \
		/Users/volodymyr/QtSDK/Desktop/Qt/474/gcc/mkspecs/features/debug.prf \
		/Users/volodymyr/QtSDK/Desktop/Qt/474/gcc/mkspecs/features/default_post.prf \
		/Users/volodymyr/QtSDK/Desktop/Qt/474/gcc/mkspecs/features/mac/default_post.prf \
		/Users/volodymyr/QtSDK/Desktop/Qt/474/gcc/mkspecs/features/mac/x86_64.prf \
		/Users/volodymyr/QtSDK/Desktop/Qt/474/gcc/mkspecs/features/mac/objective_c.prf \
		/Users/volodymyr/QtSDK/Desktop/Qt/474/gcc/mkspecs/features/warn_on.prf \
		/Users/volodymyr/QtSDK/Desktop/Qt/474/gcc/mkspecs/features/qt.prf \
		/Users/volodymyr/QtSDK/Desktop/Qt/474/gcc/mkspecs/features/unix/thread.prf \
		/Users/volodymyr/QtSDK/Desktop/Qt/474/gcc/mkspecs/features/moc.prf \
		/Users/volodymyr/QtSDK/Desktop/Qt/474/gcc/mkspecs/features/mac/rez.prf \
		/Users/volodymyr/QtSDK/Desktop/Qt/474/gcc/mkspecs/features/mac/sdk.prf \
		/Users/volodymyr/QtSDK/Desktop/Qt/474/gcc/mkspecs/features/resources.prf \
		/Users/volodymyr/QtSDK/Desktop/Qt/474/gcc/mkspecs/features/uic.prf \
		/Users/volodymyr/QtSDK/Desktop/Qt/474/gcc/mkspecs/features/yacc.prf \
		/Users/volodymyr/QtSDK/Desktop/Qt/474/gcc/mkspecs/features/lex.prf \
		/Users/volodymyr/QtSDK/Desktop/Qt/474/gcc/mkspecs/features/include_source_dir.prf
	$(QMAKE) -spec /Users/volodymyr/QtSDK/Desktop/Qt/474/gcc/mkspecs/macx-g++42 -o Makefile labs.pro
/Users/volodymyr/QtSDK/Desktop/Qt/474/gcc/mkspecs/common/unix.conf:
/Users/volodymyr/QtSDK/Desktop/Qt/474/gcc/mkspecs/common/mac.conf:
/Users/volodymyr/QtSDK/Desktop/Qt/474/gcc/mkspecs/common/mac-g++.conf:
/Users/volodymyr/QtSDK/Desktop/Qt/474/gcc/mkspecs/qconfig.pri:
/Users/volodymyr/QtSDK/Desktop/Qt/474/gcc/mkspecs/modules/qt_webkit_version.pri:
/Users/volodymyr/QtSDK/Desktop/Qt/474/gcc/mkspecs/features/qt_functions.prf:
/Users/volodymyr/QtSDK/Desktop/Qt/474/gcc/mkspecs/features/qt_config.prf:
/Users/volodymyr/QtSDK/Desktop/Qt/474/gcc/mkspecs/features/exclusive_builds.prf:
/Users/volodymyr/QtSDK/Desktop/Qt/474/gcc/mkspecs/features/default_pre.prf:
/Users/volodymyr/QtSDK/Desktop/Qt/474/gcc/mkspecs/features/mac/default_pre.prf:
/Users/volodymyr/QtSDK/Desktop/Qt/474/gcc/mkspecs/features/mac/dwarf2.prf:
/Users/volodymyr/QtSDK/Desktop/Qt/474/gcc/mkspecs/features/debug.prf:
/Users/volodymyr/QtSDK/Desktop/Qt/474/gcc/mkspecs/features/default_post.prf:
/Users/volodymyr/QtSDK/Desktop/Qt/474/gcc/mkspecs/features/mac/default_post.prf:
/Users/volodymyr/QtSDK/Desktop/Qt/474/gcc/mkspecs/features/mac/x86_64.prf:
/Users/volodymyr/QtSDK/Desktop/Qt/474/gcc/mkspecs/features/mac/objective_c.prf:
/Users/volodymyr/QtSDK/Desktop/Qt/474/gcc/mkspecs/features/warn_on.prf:
/Users/volodymyr/QtSDK/Desktop/Qt/474/gcc/mkspecs/features/qt.prf:
/Users/volodymyr/QtSDK/Desktop/Qt/474/gcc/mkspecs/features/unix/thread.prf:
/Users/volodymyr/QtSDK/Desktop/Qt/474/gcc/mkspecs/features/moc.prf:
/Users/volodymyr/QtSDK/Desktop/Qt/474/gcc/mkspecs/features/mac/rez.prf:
/Users/volodymyr/QtSDK/Desktop/Qt/474/gcc/mkspecs/features/mac/sdk.prf:
/Users/volodymyr/QtSDK/Desktop/Qt/474/gcc/mkspecs/features/resources.prf:
/Users/volodymyr/QtSDK/Desktop/Qt/474/gcc/mkspecs/features/uic.prf:
/Users/volodymyr/QtSDK/Desktop/Qt/474/gcc/mkspecs/features/yacc.prf:
/Users/volodymyr/QtSDK/Desktop/Qt/474/gcc/mkspecs/features/lex.prf:
/Users/volodymyr/QtSDK/Desktop/Qt/474/gcc/mkspecs/features/include_source_dir.prf:
qmake:  FORCE
	@$(QMAKE) -spec /Users/volodymyr/QtSDK/Desktop/Qt/474/gcc/mkspecs/macx-g++42 -o Makefile labs.pro

labs.app/Contents/PkgInfo: 
	@$(CHK_DIR_EXISTS) labs.app/Contents || $(MKDIR) labs.app/Contents 
	@$(DEL_FILE) labs.app/Contents/PkgInfo
	@echo "APPL????" >labs.app/Contents/PkgInfo
labs.app/Contents/Resources/empty.lproj: 
	@$(CHK_DIR_EXISTS) labs.app/Contents/Resources || $(MKDIR) labs.app/Contents/Resources 
	@touch labs.app/Contents/Resources/empty.lproj
	
labs.app/Contents/Info.plist: 
	@$(CHK_DIR_EXISTS) labs.app/Contents || $(MKDIR) labs.app/Contents 
	@$(DEL_FILE) labs.app/Contents/Info.plist
	@sed -e "s,@ICON@,,g" -e "s,@EXECUTABLE@,labs,g" -e "s,@TYPEINFO@,????,g" /Users/volodymyr/QtSDK/Desktop/Qt/474/gcc/mkspecs/macx-g++42/Info.plist.app >labs.app/Contents/Info.plist
dist: 
	@$(CHK_DIR_EXISTS) .tmp/labs1.0.0 || $(MKDIR) .tmp/labs1.0.0 
	$(COPY_FILE) --parents $(SOURCES) $(DIST) .tmp/labs1.0.0/ && $(COPY_FILE) --parents mainwindow.h crypto.h .tmp/labs1.0.0/ && $(COPY_FILE) --parents main.cpp mainwindow.cpp crypto.cpp .tmp/labs1.0.0/ && $(COPY_FILE) --parents mainwindow.ui .tmp/labs1.0.0/ && (cd `dirname .tmp/labs1.0.0` && $(TAR) labs1.0.0.tar labs1.0.0 && $(COMPRESS) labs1.0.0.tar) && $(MOVE) `dirname .tmp/labs1.0.0`/labs1.0.0.tar.gz . && $(DEL_FILE) -r .tmp/labs1.0.0


clean:compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


####### Sub-libraries

distclean: clean
	-$(DEL_FILE) -r labs.app
	-$(DEL_FILE) Makefile


check: first

mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

compiler_objective_c_make_all:
compiler_objective_c_clean:
compiler_moc_header_make_all: moc_mainwindow.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_mainwindow.cpp
moc_mainwindow.cpp: crypto.h \
		mainwindow.h
	/Users/volodymyr/QtSDK/Desktop/Qt/474/gcc/bin/moc $(DEFINES) $(INCPATH) -D__APPLE__ -D__GNUC__ mainwindow.h -o moc_mainwindow.cpp

compiler_rcc_make_all:
compiler_rcc_clean:
compiler_image_collection_make_all: qmake_image_collection.cpp
compiler_image_collection_clean:
	-$(DEL_FILE) qmake_image_collection.cpp
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_rez_source_make_all:
compiler_rez_source_clean:
compiler_uic_make_all: ui_mainwindow.h
compiler_uic_clean:
	-$(DEL_FILE) ui_mainwindow.h
ui_mainwindow.h: mainwindow.ui
	/Users/volodymyr/QtSDK/Desktop/Qt/474/gcc/bin/uic mainwindow.ui -o ui_mainwindow.h

compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_moc_header_clean compiler_uic_clean 

####### Compile

main.o: main.cpp mainwindow.h \
		crypto.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o main.cpp

mainwindow.o: mainwindow.cpp mainwindow.h \
		crypto.h \
		ui_mainwindow.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o mainwindow.o mainwindow.cpp

crypto.o: crypto.cpp crypto.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o crypto.o crypto.cpp

moc_mainwindow.o: moc_mainwindow.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_mainwindow.o moc_mainwindow.cpp

####### Install

install:   FORCE

uninstall:   FORCE

FORCE:

